services:
  app:
    container_name: challenge_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./src/main:/app/src/main
    restart: always
    networks:
      - challenge_network
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    container_name: challenge_mariadb
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    ports:
      - '3306:3306'
    networks:
        - challenge_network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      interval: 1m
      timeout: 5s
      retries: 3
networks:
  challenge_network:
    driver: bridge